### PR TITLE
Added RB3 Pro Guitar/Bass version of Your Love

### PR DESCRIPTION
**Pull request by kevinturner**
This isn't an ultimate CON like the others since I wasn't quite sure how to make that, but this is a recompiled version of the on-disc song, now with full Pro Guitar/Bass support.

### CODE REVIEW

**Comment by C0Assassin** [comment]
I'll reupload this once it's fixed.

As it is now, its currently a whole new con package thats been ran thru Onyx and Magma, and that is not what I would recommend doing. Pro upgrades should be appended to the existing con packages, and saved as RB3 cons. (This can all be done in C3 Con Tools)

**Comment by kevinturner** [comment]
Thanks for the heads up, I was able to make a version on my own that matched the one you made.

**Comment by C0Assassin** [comment]
Nice. I've gone and added a fixed version already into the repo.

**Comment by C0Assassin** [comment]
> Thanks for the heads up, I was able to make a version on my own that matched the one you made.
> 
> 

Also, if you dont mind me asking, are you the one who charted these pro charts?

**Comment by kevinturner** [comment]
This was all made by me. Started from Rocksmith (there's really only one way to play these parts), but I had to do a fair bit of work to match the part transitions that the Rock Band team added, and to make arpeggios work the way you would expect in Rock Band. Also made all of the difficulties for this one manually, which I'd say went _mostly_ well except for trying to simplify the ending guitar solo for Hard.

**Comment by C0Assassin** [comment]
> This was all made by me. Started from Rocksmith (there's really only one way to play these parts), but I had to do a fair bit of work to match the part transitions that the Rock Band team added, and to make arpeggios work the way you would expect in Rock Band. Also made all of the difficulties for this one manually, which I'd say went _mostly_ well except for trying to simplify the ending guitar solo for Hard.

Wow, that is fantastic and some really nice work. Ill update the dta tomorrow to include ur name as the charter for the pro instruments.

**Pull request merged**
